-- Tables to support Upcoming Tests staging and production data

CREATE TABLE IF NOT EXISTS UpcomingTests_Staging (
  `Parent Customer` VARCHAR(255),
  `Customer` VARCHAR(255),
  `Customer Phone` VARCHAR(255),
  `Customer Email` VARCHAR(255),
  `Customer Address Line 1` VARCHAR(255),
  `Customer Address Line 2` VARCHAR(255),
  `Customer City` VARCHAR(255),
  `Customer State` VARCHAR(255),
  `Customer Zip` VARCHAR(50),
  `Serial` VARCHAR(255),
  `Syncta Id` VARCHAR(255),
  `Containment` VARCHAR(255),
  `Last Tested On` DATE,
  `Next Test Due` DATE,
  `Assembly Status` VARCHAR(255),
  `Assembly Type` VARCHAR(255),
  `Assembly Manufacturer` VARCHAR(255),
  `Assembly Model` VARCHAR(255),
  `Assembly Size` VARCHAR(255),
  `Assembly Location` VARCHAR(255),
  `Install Date` DATE,
  `Testing Frequency` VARCHAR(255),
  `Notification Frequency` VARCHAR(255),
  `Last Notified At` DATE,
  `Notification Month` VARCHAR(255),
  `Price` DECIMAL(10,2),
  `Test Yearly` VARCHAR(255),
  `Water Purveyor` VARCHAR(255),
  `Service Location Name` VARCHAR(255),
  `Service Location Phone` VARCHAR(255),
  `Service Location Email` VARCHAR(255),
  `Service Location Address Line 1` VARCHAR(255),
  `Service Location Address Line 2` VARCHAR(255),
  `Service Location City` VARCHAR(255),
  `Service Location State` VARCHAR(255),
  `Service Location Zip` VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS UpcomingTests (
  `Parent Customer` VARCHAR(255),
  `Customer` VARCHAR(255),
  `Note` TEXT,
  `Action Date` DATE,
  `Customer Phone` VARCHAR(255),
  `Customer Email` VARCHAR(255),
  `Customer Address Line 1` VARCHAR(255),
  `Customer Address Line 2` VARCHAR(255),
  `Customer City` VARCHAR(255),
  `Customer State` VARCHAR(255),
  `Customer Zip` VARCHAR(50),
  `Serial` VARCHAR(255),
  `Syncta Id` VARCHAR(255),
  `Containment` VARCHAR(255),
  `Last Tested On` DATE,
  `Next Test Due` DATE,
  `Assembly Status` VARCHAR(255),
  `Assembly Type` VARCHAR(255),
  `Assembly Manufacturer` VARCHAR(255),
  `Assembly Model` VARCHAR(255),
  `Assembly Size` VARCHAR(255),
  `Assembly Location` VARCHAR(255),
  `Install Date` DATE,
  `Testing Frequency` VARCHAR(255),
  `Notification Frequency` VARCHAR(255),
  `Last Notified At` DATE,
  `Notification Month` VARCHAR(255),
  `Price` DECIMAL(10,2),
  `Test Yearly` VARCHAR(255),
  `Water Purveyor` VARCHAR(255),
  `Service Location Name` VARCHAR(255),
  `Service Location Phone` VARCHAR(255),
  `Service Location Email` VARCHAR(255),
  `Service Location Address Line 1` VARCHAR(255),
  `Service Location Address Line 2` VARCHAR(255),
  `Service Location City` VARCHAR(255),
  `Service Location State` VARCHAR(255),
  `Service Location Zip` VARCHAR(50),
  PRIMARY KEY (`Customer Address Line 1`, `Serial`, `Assembly Location`)
);
